const people = {
  athletes: [
    {
      name: "Michael Jordan",
      age: 61,
      nationality: "American",
      alive: true,
      continent: "North America",
      field: "Basketball",
      knownFor: "Chicago Bulls / NBA legend",
      success: "Global superstar",
      media: "Sports",
      hints: ["Basketball legend", "Chicago Bulls", "GOAT debate"]
    },
    {
      name: "LeBron James",
      age: 40,
      nationality: "American",
      alive: true,
      continent: "North America",
      field: "Basketball",
      knownFor: "NBA dominance",
      success: "Global superstar",
      media: "Sports",
      hints: ["NBA star", "Multiple championships", "Still active"]
    },
    {
      name: "Lionel Messi",
      age: 37,
      nationality: "Argentinian",
      alive: true,
      continent: "South America",
      field: "Football",
      knownFor: "World Cup 2022",
      success: "Global superstar",
      media: "Sports",
      hints: ["Football legend", "World Cup winner", "Inter Miami"]
    },
    {
      name: "Cristiano Ronaldo",
      age: 40,
      nationality: "Portuguese",
      alive: true,
      continent: "Europe",
      field: "Football",
      knownFor: "Champions League",
      success: "Global superstar",
      media: "Sports",
      hints: ["Football icon", "Al Nassr", "Goal machine"]
    },
    {
      name: "Serena Williams",
      age: 43,
      nationality: "American",
      alive: true,
      continent: "North America",
      field: "Tennis",
      knownFor: "Grand Slams",
      success: "Legend",
      media: "Sports",
      hints: ["Tennis legend", "Grand Slam winner", "Dominant athlete"]
    },

    {
      name: "Stephen Curry",
      age: 37,
      nationality: "American",
      alive: true,
      continent: "North America",
      field: "Basketball",
      knownFor: "Golden State Warriors / 3-point shooting",
      success: "Global superstar",
      media: "Sports",
      hints: ["3-point king", "Warriors", "NBA MVP"]
    },
    {
      name: "Kevin Durant",
      age: 36,
      nationality: "American",
      alive: true,
      continent: "North America",
      field: "Basketball",
      knownFor: "Scoring ability",
      success: "Global superstar",
      media: "Sports",
      hints: ["Slim Reaper", "NBA scorer", "Multiple teams"]
    },
    {
      name: "Kobe Bryant",
      age: 41,
      nationality: "American",
      alive: false,
      continent: "North America",
      field: "Basketball",
      knownFor: "Lakers legend",
      success: "Legend",
      media: "Sports",
      hints: ["Mamba Mentality", "Lakers", "81 points"]
    },
    {
      name: "Shaquille O'Neal",
      age: 53,
      nationality: "American",
      alive: true,
      continent: "North America",
      field: "Basketball",
      knownFor: "Dominant center",
      success: "Legend",
      media: "Sports",
      hints: ["Shaq", "Lakers dominance", "NBA giant"]
    },
    {
      name: "Giannis Antetokounmpo",
      age: 30,
      nationality: "Greek",
      alive: true,
      continent: "Europe",
      field: "Basketball",
      knownFor: "Milwaukee Bucks star",
      success: "Global superstar",
      media: "Sports",
      hints: ["Greek Freak", "NBA MVP", "Bucks"]
    },
    {
      name: "Luka Dončić",
      age: 25,
      nationality: "Slovenian",
      alive: true,
      continent: "Europe",
      field: "Basketball",
      knownFor: "Dallas Mavericks star",
      success: "Global superstar",
      media: "Sports",
      hints: ["Young NBA star", "Triple-doubles", "Mavericks"]
    },
    {
      name: "Nikola Jokić",
      age: 29,
      nationality: "Serbian",
      alive: true,
      continent: "Europe",
      field: "Basketball",
      knownFor: "Denver Nuggets MVP",
      success: "Global superstar",
      media: "Sports",
      hints: ["Joker", "NBA MVP", "Passing big man"]
    },
    {
      name: "Joel Embiid",
      age: 30,
      nationality: "Cameroonian",
      alive: true,
      continent: "Africa",
      field: "Basketball",
      knownFor: "Philadelphia 76ers",
      success: "Global superstar",
      media: "Sports",
      hints: ["Process", "NBA center", "Scoring big"]
    },
    {
      name: "James Harden",
      age: 35,
      nationality: "American",
      alive: true,
      continent: "North America",
      field: "Basketball",
      knownFor: "Step-back three",
      success: "Global superstar",
      media: "Sports",
      hints: ["Beard", "MVP", "Scoring guard"]
    },
    {
      name: "Kylian Mbappé",
      age: 26,
      nationality: "French",
      alive: true,
      continent: "Europe",
      field: "Football",
      knownFor: "World Cup winner",
      success: "Global superstar",
      media: "Sports",
      hints: ["PSG/Real Madrid", "Speed", "World Cup star"]
    },
    {
      name: "Neymar Jr",
      age: 33,
      nationality: "Brazilian",
      alive: true,
      continent: "South America",
      field: "Football",
      knownFor: "Skillful winger",
      success: "Global superstar",
      media: "Sports",
      hints: ["Brazil star", "Dribbling", "PSG legend"]
    },
    {
      name: "Erling Haaland",
      age: 24,
      nationality: "Norwegian",
      alive: true,
      continent: "Europe",
      field: "Football",
      knownFor: "Goal scoring machine",
      success: "Global superstar",
      media: "Sports",
      hints: ["Man City striker", "Goals", "Power forward"]
    },
    {
      name: "Kevin De Bruyne",
      age: 33,
      nationality: "Belgian",
      alive: true,
      continent: "Europe",
      field: "Football",
      knownFor: "Playmaking",
      success: "Global superstar",
      media: "Sports",
      hints: ["Man City", "Passing genius", "Midfield"]
    },
    {
      name: "Virgil van Dijk",
      age: 33,
      nationality: "Dutch",
      alive: true,
      continent: "Europe",
      field: "Football",
      knownFor: "Defender",
      success: "Global superstar",
      media: "Sports",
      hints: ["Liverpool", "Center back", "Defensive wall"]
    },
    {
      name: "Ronaldinho",
      age: 45,
      nationality: "Brazilian",
      alive: true,
      continent: "South America",
      field: "Football",
      knownFor: "Skill and flair",
      success: "Legend",
      media: "Sports",
      hints: ["Smile", "Barcelona legend", "Dribbling wizard"]
    },
    {
      name: "David Beckham",
      age: 50,
      nationality: "British",
      alive: true,
      continent: "Europe",
      field: "Football",
      knownFor: "Free kicks",
      success: "Global superstar",
      media: "Sports",
      hints: ["MLS influence", "Fashion icon", "England captain"]
    },
    {
      name: "Roger Federer",
      age: 43,
      nationality: "Swiss",
      alive: true,
      continent: "Europe",
      field: "Tennis",
      knownFor: "Grand Slam titles",
      success: "Legend",
      media: "Sports",
      hints: ["Elegant tennis", "Wimbledon", "GOAT debate"]
    },
    {
      name: "Rafael Nadal",
      age: 38,
      nationality: "Spanish",
      alive: true,
      continent: "Europe",
      field: "Tennis",
      knownFor: "Clay dominance",
      success: "Legend",
      media: "Sports",
      hints: ["French Open king", "Clay courts", "Intensity"]
    },
    {
      name: "Novak Djokovic",
      age: 37,
      nationality: "Serbian",
      alive: true,
      continent: "Europe",
      field: "Tennis",
      knownFor: "Grand Slam record chase",
      success: "Legend",
      media: "Sports",
      hints: ["Consistency", "Grand Slam leader", "Tennis rivalry"]
    },
    {
      name: "Usain Bolt",
      age: 39,
      nationality: "Jamaican",
      alive: true,
      continent: "North America",
      field: "Athletics",
      knownFor: "Fastest sprinter",
      success: "Legend",
      media: "Sports",
      hints: ["Lightning Bolt", "Olympics", "100m record"]
    },
    {
      name: "Simone Biles",
      age: 28,
      nationality: "American",
      alive: true,
      continent: "North America",
      field: "Gymnastics",
      knownFor: "Olympic medals",
      success: "Global superstar",
      media: "Sports",
      hints: ["Gymnastics GOAT", "Olympics", "Gold medals"]
    },
    {
      name: "Tom Brady",
      age: 47,
      nationality: "American",
      alive: true,
      continent: "North America",
      field: "American Football",
      knownFor: "NFL championships",
      success: "Legend",
      media: "Sports",
      hints: ["7 Super Bowls", "Patriots", "GOAT QB"]
    },
    {
      name: "Patrick Mahomes",
      age: 29,
      nationality: "American",
      alive: true,
      continent: "North America",
      field: "American Football",
      knownFor: "Kansas City Chiefs",
      success: "Global superstar",
      media: "Sports",
      hints: ["Chiefs QB", "Super Bowl wins", "Arm talent"]
    },
    {
      name: "Mike Tyson",
      age: 58,
      nationality: "American",
      alive: true,
      continent: "North America",
      field: "Boxing",
      knownFor: "Youngest heavyweight champion",
      success: "Legend",
      media: "Sports",
      hints: ["Iron Mike", "Knockouts", "Boxing legend"]
    },
    {
      name: "Floyd Mayweather",
      age: 48,
      nationality: "American",
      alive: true,
      continent: "North America",
      field: "Boxing",
      knownFor: "Undefeated record",
      success: "Legend",
      media: "Sports",
      hints: ["Money Mayweather", "Defense", "Undefeated"]
    },
    {
      name: "Manny Pacquiao",
      age: 46,
      nationality: "Filipino",
      alive: true,
      continent: "Asia",
      field: "Boxing",
      knownFor: "Multi-division champion",
      success: "Legend",
      media: "Sports",
      hints: ["Pac-Man", "Boxing hero", "Champion"]
    },
    {
      name: "Conor McGregor",
      age: 36,
      nationality: "Irish",
      alive: true,
      continent: "Europe",
      field: "MMA",
      knownFor: "UFC star",
      success: "Global superstar",
      media: "Sports",
      hints: ["UFC champ", "Notorious", "Fighting style"]
    },
    {
      name: "Lewis Hamilton",
      age: 40,
      nationality: "British",
      alive: true,
      continent: "Europe",
      field: "Formula 1",
      knownFor: "F1 championships",
      success: "Global superstar",
      media: "Sports",
      hints: ["Mercedes", "F1 champion", "Speed racing"]
    },
    {
      name: "Max Verstappen",
      age: 27,
      nationality: "Dutch",
      alive: true,
      continent: "Europe",
      field: "Formula 1",
      knownFor: "F1 dominance",
      success: "Global superstar",
      media: "Sports",
      hints: ["Red Bull", "F1 champion", "Racing prodigy"]
    },
    {
      name: "Zlatan Ibrahimovic",
      age: 43,
      nationality: "Swedish",
      alive: true,
      continent: "Europe",
      field: "Football",
      knownFor: "Powerful striker",
      success: "Global superstar",
      media: "Sports",
      hints: ["Confidence", "Goals", "Milan/PSG"]
    }
  ],

  Musicians: [
    {
      name: "Taylor Swift",
      age: 35,
      nationality: "American",
      alive: true,
      continent: "North America",
      field: "Music",
      knownFor: "Eras Tour",
      success: "Global superstar",
      media: "Music",
      hints: ["Pop star", "Eras Tour", "Re-recorded albums"]
    },
    {
      name: "Drake",
      age: 38,
      nationality: "Canadian",
      alive: true,
      continent: "North America",
      field: "Music",
      knownFor: "OVO Sound",
      success: "Global superstar",
      media: "Music",
      hints: ["Rap artist", "Started on TV", "OVO"]
    },
    {
      name: "Beyoncé",
      age: 43,
      nationality: "American",
      alive: true,
      continent: "North America",
      field: "Music",
      knownFor: "Renaissance",
      success: "Global superstar",
      media: "Music",
      hints: ["Queen Bey", "Destiny's Child", "Renaissance"]
    },
    {
      name: "The Weeknd",
      age: 35,
      nationality: "Canadian",
      alive: true,
      continent: "North America",
      field: "Music",
      knownFor: "Blinding Lights",
      success: "Global superstar",
      media: "Music",
      hints: ["Pop/R&B", "XO", "Blinding Lights"]
    },
    {
      name: "Bad Bunny",
      age: 31,
      nationality: "Puerto Rican",
      alive: true,
      continent: "North America",
      field: "Music",
      knownFor: "Latin trap",
      success: "Global superstar",
      media: "Music",
      hints: ["Latin artist", "Spotify king", "WWE cameo"]
    },

    {
      name: "Eminem",
      age: 52,
      nationality: "American",
      alive: true,
      continent: "North America",
      field: "Music",
      knownFor: "Rap god",
      success: "Legend",
      media: "Music",
      hints: ["Slim Shady", "Rap battle", "Detroit"]
    },
    {
      name: "Rihanna",
      age: 37,
      nationality: "Barbadian",
      alive: true,
      continent: "North America",
      field: "Music",
      knownFor: "Fenty brand",
      success: "Global superstar",
      media: "Music",
      hints: ["Pop icon", "Fenty", "Umbrella"]
    },
    {
      name: "Justin Bieber",
      age: 31,
      nationality: "Canadian",
      alive: true,
      continent: "North America",
      field: "Music",
      knownFor: "Teen pop star",
      success: "Global superstar",
      media: "Music",
      hints: ["Baby song", "YouTube discovery", "Pop star"]
    },
    {
      name: "Lady Gaga",
      age: 39,
      nationality: "American",
      alive: true,
      continent: "North America",
      field: "Music",
      knownFor: "Pop reinvention",
      success: "Global superstar",
      media: "Music",
      hints: ["Poker Face", "Actress", "Unique style"]
    },
    {
      name: "Ed Sheeran",
      age: 34,
      nationality: "British",
      alive: true,
      continent: "Europe",
      field: "Music",
      knownFor: "Acoustic pop",
      success: "Global superstar",
      media: "Music",
      hints: ["Shape of You", "Guitar loop", "Singer-songwriter"]
    },
    {
      name: "Ariana Grande",
      age: 32,
      nationality: "American",
      alive: true,
      continent: "North America",
      field: "Music",
      knownFor: "Vocal range",
      success: "Global superstar",
      media: "Music",
      hints: ["High notes", "Victorious", "Pop diva"]
    },
    {
      name: "Travis Scott",
      age: 33,
      nationality: "American",
      alive: true,
      continent: "North America",
      field: "Music",
      knownFor: "Astroworld",
      success: "Global superstar",
      media: "Music",
      hints: ["Rap shows", "Sicko Mode", "Astroworld"]
    },
    {
      name: "Kanye West",
      age: 47,
      nationality: "American",
      alive: true,
      continent: "North America",
      field: "Music",
      knownFor: "Yeezy",
      success: "Global superstar",
      media: "Music",
      hints: ["Ye", "Producer", "Fashion"]
    },
    {
      name: "Jay-Z",
      age: 55,
      nationality: "American",
      alive: true,
      continent: "North America",
      field: "Music",
      knownFor: "Roc Nation",
      success: "Legend",
      media: "Music",
      hints: ["Rapper", "Business mogul", "Beyoncé husband"]
    },
    {
      name: "Kendrick Lamar",
      age: 37,
      nationality: "American",
      alive: true,
      continent: "North America",
      field: "Music",
      knownFor: "Lyrical rap",
      success: "Global superstar",
      media: "Music",
      hints: ["Pulitzer winner", "To Pimp a Butterfly", "Hip-hop"]
    },
    {
      name: "J. Cole",
      age: 39,
      nationality: "American",
      alive: true,
      continent: "North America",
      field: "Music",
      knownFor: "Storytelling rap",
      success: "Global superstar",
      media: "Music",
      hints: ["Dreamville", "No features", "Lyricist"]
    },
    {
      name: "SZA",
      age: 35,
      nationality: "American",
      alive: true,
      continent: "North America",
      field: "Music",
      knownFor: "Ctrl album",
      success: "Global superstar",
      media: "Music",
      hints: ["R&B singer", "Kill Bill", "Soulful"]
    },
    {
      name: "Billie Eilish",
      age: 23,
      nationality: "American",
      alive: true,
      continent: "North America",
      field: "Music",
      knownFor: "Ocean Eyes",
      success: "Global superstar",
      media: "Music",
      hints: ["Dark pop", "Grammy winner", "Youth star"]
    },
    {
      name: "Post Malone",
      age: 29,
      nationality: "American",
      alive: true,
      continent: "North America",
      field: "Music",
      knownFor: "Rockstar",
      success: "Global superstar",
      media: "Music",
      hints: ["Blending genres", "Face tattoos", "Circles"]
    },
    {
      name: "Bruno Mars",
      age: 39,
      nationality: "American",
      alive: true,
      continent: "North America",
      field: "Music",
      knownFor: "Uptown Funk",
      success: "Global superstar",
      media: "Music",
      hints: ["Performance", "Funk pop", "Versatile"]
    },
    {
      name: "Adele",
      age: 36,
      nationality: "British",
      alive: true,
      continent: "Europe",
      field: "Music",
      knownFor: "21 album",
      success: "Global superstar",
      media: "Music",
      hints: ["Power vocals", "Hello", "Ballads"]
    },
    {
      name: "Harry Styles",
      age: 31,
      nationality: "British",
      alive: true,
      continent: "Europe",
      field: "Music",
      knownFor: "One Direction",
      success: "Global superstar",
      media: "Music",
      hints: ["Boy band", "Solo career", "Fashion"]
    },
    {
      name: "Dua Lipa",
      age: 29,
      nationality: "British",
      alive: true,
      continent: "Europe",
      field: "Music",
      knownFor: "Future Nostalgia",
      success: "Global superstar",
      media: "Music",
      hints: ["Dance pop", "Levitating", "Disco vibe"]
    },
    {
      name: "Olivia Rodrigo",
      age: 22,
      nationality: "American",
      alive: true,
      continent: "North America",
      field: "Music",
      knownFor: "SOUR",
      success: "Global superstar",
      media: "Music",
      hints: ["Driver’s License", "Gen Z pop", "Emotional"]
    },
    {
      name: "Shawn Mendes",
      age: 26,
      nationality: "Canadian",
      alive: true,
      continent: "North America",
      field: "Music",
      knownFor: "Stitches",
      success: "Global superstar",
      media: "Music",
      hints: ["Acoustic pop", "Instagram start", "Touring"]
    },
    {
      name: "Coldplay",
      age: 48,
      nationality: "British",
      alive: true,
      continent: "Europe",
      field: "Music",
      knownFor: "Fix You",
      success: "Global superstar",
      media: "Music",
      hints: ["Band", "Viva La Vida", "Arena shows"]
    },
    {
      name: "BTS",
      age: 30,
      nationality: "South Korean",
      alive: true,
      continent: "Asia",
      field: "Music",
      knownFor: "K-pop global rise",
      success: "Global superstar",
      media: "Music",
      hints: ["K-pop", "Army fans", "Billboard"]
    },
    {
      name: "BLACKPINK",
      age: 28,
      nationality: "South Korean",
      alive: true,
      continent: "Asia",
      field: "Music",
      knownFor: "K-pop girl group",
      success: "Global superstar",
      media: "Music",
      hints: ["K-pop group", "Coachella", "Pink Venom"]
    },
    {
      name: "Shakira",
      age: 48,
      nationality: "Colombian",
      alive: true,
      continent: "South America",
      field: "Music",
      knownFor: "Hips Don't Lie",
      success: "Global superstar",
      media: "Music",
      hints: ["Latin pop", "Dancing", "World Cup songs"]
    },
    {
      name: "J Balvin",
      age: 40,
      nationality: "Colombian",
      alive: true,
      continent: "South America",
      field: "Music",
      knownFor: "Reggaeton",
      success: "Global superstar",
      media: "Music",
      hints: ["Latin urban", "Mi Gente", "Colombian star"]
    },
    {
      name: "Maluma",
      age: 31,
      nationality: "Colombian",
      alive: true,
      continent: "South America",
      field: "Music",
      knownFor: "Latin pop",
      success: "Global superstar",
      media: "Music",
      hints: ["Reggaeton singer", "Pretty Boy", "Latin hits"]
    },
    {
      name: "Doja Cat",
      age: 29,
      nationality: "American",
      alive: true,
      continent: "North America",
      field: "Music",
      knownFor: "Say So",
      success: "Global superstar",
      media: "Music",
      hints: ["Genre blending", "Viral hits", "Rap pop"]
    },
    {
      name: "Lizzo",
      age: 36,
      nationality: "American",
      alive: true,
      continent: "North America",
      field: "Music",
      knownFor: "Good as Hell",
      success: "Global superstar",
      media: "Music",
      hints: ["Body positivity", "Flute", "Pop funk"]
    },
    {
      name: "Nicki Minaj",
      age: 42,
      nationality: "Trinidadian",
      alive: true,
      continent: "North America",
      field: "Music",
      knownFor: "Pink Friday",
      success: "Global superstar",
      media: "Music",
      hints: ["Queen of rap", "Verses", "Barbie persona"]
    },
    {
      name: "Calvin Harris",
      age: 41,
      nationality: "Scottish",
      alive: true,
      continent: "Europe",
      field: "Music",
      knownFor: "EDM hits",
      success: "Global superstar",
      media: "Music",
      hints: ["DJ", "Electronic music", "Summer hits"]
    }
  ],

  Actors: [
    {
      name: "Leonardo DiCaprio",
      age: 50,
      nationality: "American",
      alive: true,
      continent: "North America",
      field: "Film",
      knownFor: "Titanic",
      success: "Global superstar",
      media: "Film",
      hints: ["Titanic", "Oscar winner", "Wolf of Wall Street"]
    },
    {
      name: "Zendaya",
      age: 28,
      nationality: "American",
      alive: true,
      continent: "North America",
      field: "Film",
      knownFor: "Euphoria",
      success: "Global superstar",
      media: "Film",
      hints: ["Euphoria", "Spider-Man", "Disney start"]
    },
    {
      name: "Tom Holland",
      age: 28,
      nationality: "British",
      alive: true,
      continent: "Europe",
      field: "Film",
      knownFor: "Spider-Man",
      success: "Global superstar",
      media: "Film",
      hints: ["Marvel actor", "Spider-Man", "UK actor"]
    },
    {
      name: "Denzel Washington",
      age: 70,
      nationality: "American",
      alive: true,
      continent: "North America",
      field: "Film",
      knownFor: "Training Day",
      success: "Legend",
      media: "Film",
      hints: ["Oscar winner", "Training Day", "Veteran actor"]
    },

    {
      name: "Robert Downey Jr.",
      age: 60,
      nationality: "American",
      alive: true,
      continent: "North America",
      field: "Film",
      knownFor: "Iron Man",
      success: "Global superstar",
      media: "Film",
      hints: ["Marvel", "Tony Stark", "Avengers"]
    },
    {
      name: "Chris Evans",
      age: 43,
      nationality: "American",
      alive: true,
      continent: "North America",
      field: "Film",
      knownFor: "Captain America",
      success: "Global superstar",
      media: "Film",
      hints: ["Marvel", "Shield", "Avengers"]
    },
    {
      name: "Chris Hemsworth",
      age: 41,
      nationality: "Australian",
      alive: true,
      continent: "Australia",
      field: "Film",
      knownFor: "Thor",
      success: "Global superstar",
      media: "Film",
      hints: ["Marvel", "God of Thunder", "Thor"]
    },
    {
      name: "Scarlett Johansson",
      age: 40,
      nationality: "American",
      alive: true,
      continent: "North America",
      field: "Film",
      knownFor: "Black Widow",
      success: "Global superstar",
      media: "Film",
      hints: ["Marvel", "Avengers", "Action star"]
    },
    {
      name: "Morgan Freeman",
      age: 87,
      nationality: "American",
      alive: true,
      continent: "North America",
      field: "Film",
      knownFor: "Distinct voice",
      success: "Legend",
      media: "Film",
      hints: ["Narration", "Oscar winner", "Voice"]
    },
    {
      name: "Will Smith",
      age: 56,
      nationality: "American",
      alive: true,
      continent: "North America",
      field: "Film",
      knownFor: "Men in Black",
      success: "Global superstar",
      media: "Film",
      hints: ["Fresh Prince", "Action comedy", "Hollywood"]
    },
    {
      name: "Brad Pitt",
      age: 61,
      nationality: "American",
      alive: true,
      continent: "North America",
      field: "Film",
      knownFor: "Fight Club",
      success: "Global superstar",
      media: "Film",
      hints: ["Hollywood star", "Fight Club", "Ocean’s"]
    },
    {
      name: "Angelina Jolie",
      age: 49,
      nationality: "American",
      alive: true,
      continent: "North America",
      field: "Film",
      knownFor: "Maleficent",
      success: "Global superstar",
      media: "Film",
      hints: ["Tomb Raider", "Humanitarian", "Disney villain"]
    },
    {
      name: "Johnny Depp",
      age: 61,
      nationality: "American",
      alive: true,
      continent: "North America",
      field: "Film",
      knownFor: "Pirates of the Caribbean",
      success: "Global superstar",
      media: "Film",
      hints: ["Jack Sparrow", "Pirates", "Unique roles"]
    },
    {
      name: "Emma Stone",
      age: 36,
      nationality: "American",
      alive: true,
      continent: "North America",
      field: "Film",
      knownFor: "La La Land",
      success: "Global superstar",
      media: "Film",
      hints: ["Oscar winner", "Comedy-drama", "La La Land"]
    },
    {
      name: "Emma Watson",
      age: 35,
      nationality: "British",
      alive: true,
      continent: "Europe",
      field: "Film",
      knownFor: "Harry Potter",
      success: "Global superstar",
      media: "Film",
      hints: ["Hermione", "Wizarding World", "Activist"]
    },
    {
      name: "Ryan Reynolds",
      age: 48,
      nationality: "Canadian",
      alive: true,
      continent: "North America",
      field: "Film",
      knownFor: "Deadpool",
      success: "Global superstar",
      media: "Film",
      hints: ["Comedy", "Deadpool", "Witty roles"]
    },
    {
      name: "Hugh Jackman",
      age: 56,
      nationality: "Australian",
      alive: true,
      continent: "Australia",
      field: "Film",
      knownFor: "Wolverine",
      success: "Global superstar",
      media: "Film",
      hints: ["X-Men", "Musicals", "Wolverine"]
    },
    {
      name: "Matt Damon",
      age: 54,
      nationality: "American",
      alive: true,
      continent: "North America",
      field: "Film",
      knownFor: "The Martian",
      success: "Global superstar",
      media: "Film",
      hints: ["Good Will Hunting", "Sci-fi", "Action roles"]
    },
    {
      name: "Christian Bale",
      age: 51,
      nationality: "British",
      alive: true,
      continent: "Europe",
      field: "Film",
      knownFor: "Batman trilogy",
      success: "Global superstar",
      media: "Film",
      hints: ["Method actor", "Batman", "Transformation"]
    },
    {
      name: "Margot Robbie",
      age: 34,
      nationality: "Australian",
      alive: true,
      continent: "Australia",
      field: "Film",
      knownFor: "Barbie",
      success: "Global superstar",
      media: "Film",
      hints: ["Harley Quinn", "Barbie movie", "Producer"]
    },
    {
      name: "Robert Pattinson",
      age: 38,
      nationality: "British",
      alive: true,
      continent: "Europe",
      field: "Film",
      knownFor: "Twilight / Batman",
      success: "Global superstar",
      media: "Film",
      hints: ["Vampire saga", "Batman", "Indie films"]
    },
    {
      name: "Anne Hathaway",
      age: 42,
      nationality: "American",
      alive: true,
      continent: "North America",
      field: "Film",
      knownFor: "Les Misérables",
      success: "Global superstar",
      media: "Film",
      hints: ["Princess Diaries", "Oscar winner", "Musicals"]
    },
    {
      name: "Keanu Reeves",
      age: 60,
      nationality: "Canadian",
      alive: true,
      continent: "North America",
      field: "Film",
      knownFor: "John Wick",
      success: "Global superstar",
      media: "Film",
      hints: ["Matrix", "John Wick", "Internet favorite"]
    },
    {
      name: "Samuel L Jackson",
      age: 76,
      nationality: "American",
      alive: true,
      continent: "North America",
      field: "Film",
      knownFor: "Pulp Fiction",
      success: "Global superstar",
      media: "Film",
      hints: ["Nick Fury", "Marvel", "Iconic voice"]
    }
  ],

  Tech: [
    {
      name: "Elon Musk",
      age: 54,
      nationality: "South African",
      alive: true,
      continent: "Africa",
      field: "Tech",
      knownFor: "Tesla / SpaceX",
      success: "Global superstar",
      media: "Tech",
      hints: ["Tesla", "SpaceX", "X (Twitter)"]
    },
    {
      name: "Steve Jobs",
      age: 56,
      nationality: "American",
      alive: false,
      continent: "North America",
      field: "Tech",
      knownFor: "Apple iPhone",
      success: "Legend",
      media: "Tech",
      hints: ["Apple", "iPhone", "Pixar"]
    },
    {
      name: "Mark Zuckerberg",
      age: 41,
      nationality: "American",
      alive: true,
      continent: "North America",
      field: "Tech",
      knownFor: "Facebook",
      success: "Global superstar",
      media: "Tech",
      hints: ["Meta", "Facebook", "Harvard dropout"]
    },

    {
      name: "Bill Gates",
      age: 69,
      nationality: "American",
      alive: true,
      continent: "North America",
      field: "Tech",
      knownFor: "Microsoft",
      success: "Legend",
      media: "Tech",
      hints: ["Windows", "Microsoft", "Philanthropy"]
    },
    {
      name: "Jeff Bezos",
      age: 61,
      nationality: "American",
      alive: true,
      continent: "North America",
      field: "Tech",
      knownFor: "Amazon",
      success: "Global superstar",
      media: "Tech",
      hints: ["Amazon", "E-commerce", "Blue Origin"]
    },
    {
      name: "Sundar Pichai",
      age: 52,
      nationality: "Indian",
      alive: true,
      continent: "Asia",
      field: "Tech",
      knownFor: "Google CEO",
      success: "Global superstar",
      media: "Tech",
      hints: ["Google", "Search", "Android"]
    },
    {
      name: "Satya Nadella",
      age: 57,
      nationality: "Indian",
      alive: true,
      continent: "Asia",
      field: "Tech",
      knownFor: "Microsoft CEO",
      success: "Global superstar",
      media: "Tech",
      hints: ["Cloud computing", "Azure", "Microsoft leader"]
    },
    {
      name: "Tim Cook",
      age: 64,
      nationality: "American",
      alive: true,
      continent: "North America",
      field: "Tech",
      knownFor: "Apple CEO",
      success: "Global superstar",
      media: "Tech",
      hints: ["Apple", "iPhone era", "Operations"]
    },
    {
      name: "Larry Page",
      age: 52,
      nationality: "American",
      alive: true,
      continent: "North America",
      field: "Tech",
      knownFor: "Google co-founder",
      success: "Legend",
      media: "Tech",
      hints: ["Search engine", "Google", "PageRank"]
    },
    {
      name: "Sergey Brin",
      age: 51,
      nationality: "Russian-American",
      alive: true,
      continent: "North America",
      field: "Tech",
      knownFor: "Google co-founder",
      success: "Legend",
      media: "Tech",
      hints: ["Google", "Search", "Innovation"]
    },
    {
      name: "Jack Dorsey",
      age: 48,
      nationality: "American",
      alive: true,
      continent: "North America",
      field: "Tech",
      knownFor: "Twitter",
      success: "Global superstar",
      media: "Tech",
      hints: ["Twitter", "Square", "Social media"]
    },
    {
      name: "Jensen Huang",
      age: 62,
      nationality: "Taiwanese-American",
      alive: true,
      continent: "Asia",
      field: "Tech",
      knownFor: "NVIDIA",
      success: "Global superstar",
      media: "Tech",
      hints: ["GPU", "AI chips", "NVIDIA"]
    },
    {
      name: "Sam Altman",
      age: 40,
      nationality: "American",
      alive: true,
      continent: "North America",
      field: "Tech",
      knownFor: "OpenAI",
      success: "Global superstar",
      media: "Tech",
      hints: ["AI", "ChatGPT", "OpenAI"]
    }
  ],

  Historical: [
    {
      name: "Albert Einstein",
      age: 76,
      nationality: "German",
      alive: false,
      continent: "Europe",
      field: "Science",
      knownFor: "Relativity",
      success: "Legend",
      media: "Historical",
      hints: ["Physics genius", "E=mc²", "Relativity"]
    },
    {
      name: "Isaac Newton",
      age: 84,
      nationality: "British",
      alive: false,
      continent: "Europe",
      field: "Science",
      knownFor: "Gravity",
      success: "Legend",
      media: "Historical",
      hints: ["Gravity", "Apple story", "Laws of motion"]
    },

    {
      name: "Leonardo da Vinci",
      age: 67,
      nationality: "Italian",
      alive: false,
      continent: "Europe",
      field: "Art/Science",
      knownFor: "Mona Lisa",
      success: "Legend",
      media: "Historical",
      hints: ["Renaissance", "Mona Lisa", "Inventor"]
    },
    {
      name: "Galileo Galilei",
      age: 77,
      nationality: "Italian",
      alive: false,
      continent: "Europe",
      field: "Science",
      knownFor: "Astronomy",
      success: "Legend",
      media: "Historical",
      hints: ["Telescope", "Space observation", "Physics"]
    },
    {
      name: "Nikola Tesla",
      age: 86,
      nationality: "Serbian-American",
      alive: false,
      continent: "Europe",
      field: "Science",
      knownFor: "AC electricity",
      success: "Legend",
      media: "Historical",
      hints: ["Electricity", "Tesla coil", "Eccentric inventor"]
    },
    {
      name: "Marie Curie",
      age: 66,
      nationality: "Polish-French",
      alive: false,
      continent: "Europe",
      field: "Science",
      knownFor: "Radioactivity",
      success: "Legend",
      media: "Historical",
      hints: ["Nobel Prize", "Radiation", "Chemistry"]
    },
    {
      name: "Martin Luther King Jr.",
      age: 39,
      nationality: "American",
      alive: false,
      continent: "North America",
      field: "Civil Rights",
      knownFor: "I Have a Dream",
      success: "Legend",
      media: "Historical",
      hints: ["Civil rights", "Equality", "Speech"]
    },
    {
      name: "Mahatma Gandhi",
      age: 78,
      nationality: "Indian",
      alive: false,
      continent: "Asia",
      field: "Politics",
      knownFor: "Non-violence",
      success: "Legend",
      media: "Historical",
      hints: ["Peace", "India independence", "Nonviolence"]
    },
    {
      name: "Abraham Lincoln",
      age: 56,
      nationality: "American",
      alive: false,
      continent: "North America",
      field: "Politics",
      knownFor: "US President",
      success: "Legend",
      media: "Historical",
      hints: ["Civil War", "Emancipation", "President"]
    },
    {
      name: "Julius Caesar",
      age: 55,
      nationality: "Roman",
      alive: false,
      continent: "Europe",
      field: "Politics",
      knownFor: "Roman Empire",
      success: "Legend",
      media: "Historical",
      hints: ["Rome", "Empire", "Ides of March"]
    },
    {
      name: "Napoleon Bonaparte",
      age: 51,
      nationality: "French",
      alive: false,
      continent: "Europe",
      field: "Military",
      knownFor: "French Empire",
      success: "Legend",
      media: "Historical",
      hints: ["France", "War leader", "Emperor"]
    },
    {
      name: "Cleopatra",
      age: 39,
      nationality: "Egyptian",
      alive: false,
      continent: "Africa",
      field: "Politics",
      knownFor: "Egyptian Queen",
      success: "Legend",
      media: "Historical",
      hints: ["Egypt", "Queen", "Ancient history"]
    }
  ]
};